from app.models.usuario import Usuario
from app.models.categoria import Categoria
from app.models.tecnico_categoria import TecnicoCategoria
from app.models.inventario import Inventario
from app.models.ticket import Ticket
from app.models.comentario import Comentario
from app.models.ticket_inventario import TicketInventario
from app.models.base_conocimiento import BaseConocimiento
from app.models.notificacion import Notificacion
from app.models.ticket_lectura import TicketLectura
from app.models.auditoria import Auditoria
